### ISSUE TITLE
64 bit iOS

### ISSUE THREAD

**Issue by astjohn** [Sitata/titanium-google-analytics#10]
February 1st is the deadline, but this needs taking care of before then.

**Comment by astjohn** [comment]
3.5.0.GA has just been released and so I will try to get this update out as soon as possible.
http://www.appcelerator.com/blog/2015/01/titanium-sdk-3-5-0-ga-now-available-with-64-bit-ios-support/

**Comment by soumyakantikar** [comment]
@astjohn Great. Thanks for sharing the link for 3.5.0.GA release and also working on the update for GA 64 bit iOS support.

**Comment by astjohn** [comment]
@aeikenberry, @soumyakantikar, @ottopic - I just pushed version 3.0.0 for this module and 64bit capability. Please check it out and let me know how it goes. 

Note that if you are upgrading your application to use this new version and you are experiencing build problems, try clearing out your `build` and `Resources` folders and then recompile.

**Comment by aeikenberry** [comment]
Thanks @astjohn I'll give that a shot.

**Comment by otnielgomez** [comment]
Thanks for the 64bit release!

**Comment by soumyakantikar** [comment]
Thank you for the 64-bit release.

**Comment by soumyakantikar** [comment]
I just have a question. In the manifest file for iOS, I can see that we have set the minSDK to 3.5.0.GA. Whereas when I am checking the titanium.xcconfig file, I see that it is still referred to 3.0.2.GA. Do we not update it for 3.5.0.GA?

**Comment by astjohn** [comment]
@soumyakantikar, Good call. I'm not sure if that affects the build or not, but just in case I have pushed an update with a minor version bump to the iOS side.

**Comment by pussaaon** [comment]
@astjohn  if it's possible that you set minimun sdk for android to 3.4.2 to be compatible with this module 
https://github.com/mokesmokes/titanium-android-facebook.

**Comment by astjohn** [comment]
@pussaaon, I am pretty sure that 3.5.0.GA is required for a 64bit build on iOS, which is why the major version of this module was increased. If you would like to use this module with a lower version of the Titanium SDK, then you can still use previous releases such as version `Android-2.2.0-iOS-2.1.0`, which I believe has a minimum version requirement of 3.0.2.GA

**Comment by ManjotS** [comment]
I tried clearing out the build and resources folders but I am getting this error on build for ios, no issues in android:
    [ERROR] :  Script Error Couldn't find module: GA for architecture: x86_64

I am using the latest zips from github.

**Comment by soumyakantikar** [comment]
Please see that you are using the latest zip, 3.0.2, and then build it with
3.5.0.GA. You can also check whether the .a file you are hsing has 64bit
support.

**Comment by mokesmokes** [comment]
@astjohn , @pussaaon 's request: there is no reason why the Android manifest file should specify 3.5.0.GA - it could easily be 3.4.1 for Android, which is essentially the same SDK as in 3.5.0.GA. The differences are almost all iOS only.

**Comment by soumyakantikar** [comment]
@pussaaon You can still use 3.4.1.GA to build it. 3.5.0.GA is only applicable if you are building it for iOS with 64-bit support.

**Comment by pussaaon** [comment]
thanks guys yes now we use different sdk for ios and android, they work fine :)

**Comment by pussaaon** [comment]
@astjohn  @mokesmokes  hi, guys now we are moving up to the sdk which support node 0.12.0, which is 3.5.1.Alpha at a moment,
so now it's getting more complicated to switch the sdk version when we build, have to switch both the titanium sdk version and node version, should we make this support the 3.5.1.GA for both ios and android ?

**Comment by mokesmokes** [comment]
3.5.1.GA will support my Facebook module. The required code has been merged into 3_5_X https://github.com/appcelerator/titanium_mobile/pull/6650

**Comment by astjohn** [comment]
@pussaaon, I'm not up to speed with 3.5.1.Alpha and am terribly busy at the moment with other obligations. However, I will gladly review and accept pull requests. Perhaps we can make a branch for this.

**Comment by pussaaon** [comment]
hi, @astjohn  I have updated to 3.5.1.GA , and looks like it works fine now :)
