### ISSUE TITLE
64bit compatible?

### ISSUE THREAD

**Issue by ottopic** [Sitata/titanium-google-analytics#14]
Hi,
thanks for the big work you do! That module is very important for titanium development.

Does last version is 64 bit compatible?

Best regards
Lorenzo

**Comment by soumyakantikar** [comment]
I think no. We need to wait till 3.5.0.GA is released. Once it is done, then only we can expect to get the update. See 64 bit iOS #10. astjohn mentioned that it will be done before February 1, but need to wait till the GA is released.

**Comment by astjohn** [comment]
@ottopic, @soumyakantikar is correct. I'm going to close this since I already have an issue going to track this. There is a 64bit branch that you can test out if you wish, but we can't release anything for this module until 3.5.0.GA is released.

**Comment by astjohn** [comment]
@ottopic - Actually, I just checked and 3.5.0.GA was released today. I'll try to get an update out as soon as possible.

**Comment by ottopic** [comment]
@astjohn @soumyakantikar - Thank you very much for your attention. I will try your 64bit branch too.
