### ISSUE TITLE
idfa class missing, won't collect idfa

### ISSUE THREAD

**Issue by astjohn** [Sitata/titanium-google-analytics#15]
New 64bit version has been reported as generating the following log statement:
`idfa class missing, won't collect idfa`

This warning is bad as this might prevent acceptance by apple. A possible solution is [stated here](http://stackoverflow.com/a/25568917)

**Comment by soumyakantikar** [comment]
So do we need to make any changes for the module or can we continue using 3.0.1?

**Comment by soumyakantikar** [comment]
My application does not display ay ads and also can you please let me know where this log is getting displayed?

**Comment by astjohn** [comment]
Sure. This was reported by Marco, who emailed me directly. His log was:

```
Titanium Command-Line Interface, CLI version 3.4.1, Titanium SDK version 3.5.0.GA
Copyright (c) 2012-2014, Appcelerator, Inc.  All Rights Reserved.
Please report bugs to http://jira.appcelerator.org/
Fri Jan 16 2015 10:51:45 GMT+0100 (CET)
Operating System
  Name                        = Mac OS X
  Version                     = 10.9.5
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 25769803776
Node.js
  Node.js Version             = 0.10.28
  npm Version                 = 1.4.9
Titanium CLI
  CLI Version                 = 3.4.1
Titanium SDK
  SDK Version                 = 3.5.0.GA
  SDK Path                    = /Users/marco/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA
  Target Platform             = iphone
Command
  /usr/local/bin/node /usr/local/bin/titanium --no-colors --no-progress-bars --no-prompt build --platform iphone --log-level trace --sdk 3.5.0.GA --project-dir /Users/marco/Desktop/Titanium/Glueckskeks --target simulator --ios-version 8.2 --device-family iphone --deploy-type development --sim-type iphone --sim-version 8.2 --device-id F035D20C-3983-46C9-AF46-D5CF38F4819C --skip-js-minify --skip-js-minify
[INFO] :   Found Titanium module id=analytics.google version=3.0.1 platform=iphone deploy-type=development path=/Users/marco/Library/Application Support/Titanium/modules/iphone/analytics.google/3.0.1
[INFO] :   Deploy type: development
[INFO] :   Building for target: simulator
[INFO] :   Building using iOS SDK: 8.2
[INFO] :   Building for iOS Simulator: iPhone 5s
[INFO] :   Building for device family: iphone
[INFO] :   Minimum iOS version: 7.0
[INFO] :   Debugging disabled
[INFO] :   Profiler disabled
[INFO] :   Initiating prepare phase
[INFO] :   Copying custom Info.plist from project directory
[INFO] :   Performing full rebuild
[INFO] :   Copying Xcode iOS files
...
[INFO] :   Invoking xcodebuild
[INFO] :   Finished building the application in 13s 208ms
[INFO] :   Launching iOS Simulator
[INFO] :   Project built successfully in 16s 824ms
-- Start simulator log -------------------------------------------------------
[INFO] :   Application started
[INFO] :   Glueckskeks/2.6 (3.5.0.0014f83)
[INFO] :   displayHeight: 568
[INFO] :   Allow analytics: true
[INFO] :   module is => [object analytics.google]
[INFO] :   Existing Database Version: 5
[INFO] :   Found Database Version: 5
[INFO] :   2015-01-16 10:52:02.360 Glueckskeks[96723:6737766] idfa class missing, won't collect idfa
```

I am looking into it now to see if I can reproduce.

**Comment by soumyakantikar** [comment]
Thanks for sharing the log.

I verified it from my end, but I am unable to see the log when I am
deploying my app in the simulator. Is it something that the log comes when
we are making the Google analytics server?

But during require call, the issue is not coming.

**Comment by astjohn** [comment]
I can reproduce the log, but I'm not sure what the end result will be. Here's what I know:

- In older versions of the iOS analytics SDK, the advertising stuff, IDFA, and the `libAdIdAccess.a` files were all bundled into a single library. This was creating trouble as it looked like apps were using advertising things, but were not and Apple flagged this as inconsistent. Apple was asking users to remove the advertising parts of the app since the app wasn't using them.

- Google then released an updated SDK with the IDFA stuff separated into `libAdIdAccess.a` [at version 3.03c](https://developers.google.com/analytics/devguides/collection/ios/changelog#changelog) to try to mitigate the issue.

- There are some reports that suggest this log could prevent apple from accepting an app, but these reports are sometimes older and pre-version 3.03c. It seems the log is still present for versions after 3.03c, but [at least one person](http://stackoverflow.com/a/25110554) has reported that apple still accepted the application.

- The current version of the google SDK is 3.10. Testing with this new SDK seems promising because the warning does not appear in the log anymore. I will create another release shortly for this new version.

Note that this module does not link to `libAdIdAccess.a` and does not use any of the IDFA stuff. We can add that feature when someone requests it. 

At this point, I think the main question is *will apple accept the application if the warning is present?* Unfortunately, I think we need to wait and see. If anyone has an application to submit, please let me know what happens in this issue and I will respond as soon as possible. My best suggestion will be to use the version with version 3.10 SDK which will be Android-3.0.0-iOS-3.0.2.

**Comment by soumyakantikar** [comment]
Ok. So you are going to release 3.0.2 which will not be containing the
libAdIdAccess.a linked to it.

Once it is done, then I will test it again from myend and confirm whether
the new release (3.0.2) is working properly.

We can even request the reporter of the issue to may be look into it too.

**Comment by astjohn** [comment]
@soumyakantikar - yes, but in fact, the module never had `libAdIdAccess.a` linked to it, and I will reach out to Marco to test this new version as well.

**Comment by soumyakantikar** [comment]
Eacy that is my point. I was going through the code and I did not find any
references to the IDFA.

Please let us know what Marco has to say after using 3.0.2.

Also what changes are you planning to do.

**Comment by astjohn** [comment]
@soumyakantikar, OK. Understood. Feel free to try out 3.0.2 as well. I have just released it.

**Comment by soumyakantikar** [comment]
I am having some network connectivity issue so cannot connect now. Will
check once It is back.

So this new release has reference to Advertisement library?

**Comment by astjohn** [comment]
@soumyakantikar. No reference to the Advertisement stuff. There never was.

**Comment by soumyakantikar** [comment]
So we updated the Google Analytics to 3.10?

**Comment by soumyakantikar** [comment]
The iAd franework has been added along with the IDFA library in the new
release.

Now in this case if an application is not going to display advertisements
but still use the iAD framework, then wont the application get rejected
from Apple?

Any idea regarding this?

**Comment by soumyakantikar** [comment]
@astjohn, my query is that in the project, the iAd.framework and AdSupport.framework are present. So if an application is using the module and submits the app to Apple Store and says that they are not using advertisements, won't that reject the application?

**Comment by astjohn** [comment]
@soumyakantikar, whoops! You're correct. The references were still present. I should have done this work on a separate branch. That's what I get for rushing things. I just pushed a new version of 3.0.2. Can you please check this version?

https://github.com/Sitata/titanium-google-analytics/blob/master/mobile/ios/analytics.google-iphone-3.0.2.zip

Thanks!

**Comment by soumyakantikar** [comment]
Sure. I will check it and let you know. I see that in the latest changeset
you have removed the iAd and AdSupport frameworks.

I was going through the following link and from it we actually need:
Core Data
System Configuration
Libz
Sqlite

https://developers.google.com/analytics/devguides/collection/ios/v3/

I will use the latest and let you know. Meanwhile if Marco too can test
with the latest 3.0.2 then it will be great too, cause he had reported the
original issue.

**Comment by astjohn** [comment]
@soumyakantikar You're correct. those other libraries should already be present.

**Comment by astjohn** [comment]
Marco has compiled with the latest 3.0.2 and has submitted an app to Apple. I will keep this issue open until we hear back from him or someone else that Apple is accepting the application. This might take a while.

**Comment by soumyakantikar** [comment]
Ok, great. That is good. Then we can wait and see, but I think that the new
module will get approved cause the warning is not getting displayed.
Moreover the iAd and AdSupport frameworks have been removed. So I think it
is clean. Lets hope for the best.

**Comment by soumyakantikar** [comment]
@astjohn One more point. As per the release notes from Appcelerator, we need to set the minimum iOS version for deployment target as 6.0, but currently for the project it is set to 4.0 for the release build. For debug build it has been set to 6.0. Do you think that is required to be modified?

**Comment by astjohn** [comment]
Nice catch. I just pushed an update just in case.

**Comment by soumyakantikar** [comment]
@astjohn Did we get any update from Marco as to whether the application has been approved after using the 3.0.2 module? Its been more than 2 weeks, so thought to check up.

**Comment by nascado** [comment]
Sorry not to come back earlier. 
I updated several apps in differnt countries with all 64-bit clean modules and did not had any problems from apples side.
