### ISSUE TITLE
Exception reporting.

### ISSUE THREAD

**Issue by astjohn** [Sitata/titanium-google-analytics#2]
Ensure that crash reporting is tracked.
Open API access to build crash report manually.

https://developers.google.com/analytics/devguides/collection/android/v4/exceptions
https://developers.google.com/analytics/devguides/collection/ios/v3/exceptions

**Comment by monotv** [comment]
This would support Android exception tracking?

**Comment by astjohn** [comment]
@monotv, This would follow the api outlined in the link to the developers docs. Please refer to the google documentation for more information about how to use it properly.

**Comment by mokesmokes** [comment]
See https://github.com/Sitata/titanium-google-analytics/pull/22
