### ISSUE TITLE
iOS uncaught exception crash on internet loss

### ISSUE THREAD

**Issue by Adipa** [Sitata/titanium-google-analytics#20]
Issues exists in 3.0.2 iOS module with Titanium 3.5.0.GA. If the internet goes down the module gives Network connection failed and makes 5 attempts to retry, after the 5th it crashes with a NSInternalInconsistencyException.

Steps to replicate, build on iOS with no internet and watch for when Analytics decides starts its call.

**Comment by astjohn** [comment]
Are you sure this is Google Analytics. This might in fact be Appcelerators analytics stuff. To make sure, please set analytics to false in your `tiapp.xml` file.

```
<analytics>false</analytics>
```

**Comment by soumyakantikar** [comment]
Correct. Appcelerator too has its own analytics. Do disable it and then
test it.

**Comment by Adipa** [comment]
Update on this, I set  <analytics> tag to false, it still tries to connect and times out 5 times before crashing. 
I reverted tiapp to use the older version of the module (1.0 which was 32 bit) it still runs but crashes with in the same way.
So this might not be a Google Analytics issue,  thanks for helping troubleshoot that as a possible factor though.
