### ISSUE TITLE
Getting this error in Android..

### ISSUE THREAD

**Issue by hardikamal** [Sitata/titanium-google-analytics#24]
[ERROR] :  TiApplication: (KrollRuntimeThread) [29,111] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: Couldn't load analytics.google from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.myapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.company.myapp-2, /system/lib]]]: findLibrary returned null; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: Couldn't load analytics.google from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.myapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.company.myapp-2, /system/lib]]]: findLibrary returned null
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:526)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

Please Help...

**Comment by hardikamal** [comment]
@astjohn any solution to this please

**Comment by astjohn** [comment]
@hardikamal, I'll look into it when I can. Have you tried placing the module in a clean, brand new app to see what happens then?

**Comment by hardikamal** [comment]
yeah tried with your sample app as well as creating the new one but still crashing on android

**Comment by hardikamal** [comment]
@astjohn the android module in your sample app is missing (libs) folder due to which i was getting this error...Thanks for the module...SOLVED

**Comment by astjohn** [comment]
@hardikamal - Whoops. Thanks for pointing that out. I'll have to fix that on the next update.

**Comment by parween** [comment]
@hardikamal @astjohn : Please provide the libs folder, which we can include in the android module. I have faced the same problem as reported above. Thanks in advance.

**Comment by astjohn** [comment]
@parween I have no idea what you're talking about. Are you sure you're using the release zip files? Everything is included in the release zip files.

**Comment by parween** [comment]
@astjohn :in mac Library->ApplicationSupport-> modules->android->3.1.0 , I have the following folders:
documentation
example
lib
platforms
license
analytics.google.jar
manifest
timodule.xml

Here libs folder is missing which should contain .so files. So can you guide me how to create those files.

**Comment by astjohn** [comment]
The libs folder is definitely missing, but is also most definitely included in the release zip file.
https://github.com/Sitata/titanium-google-analytics/releases/download/Android-3.1.0-iOS-3.1.0/analytics.google-android-3.1.0.zip

**Comment by parween** [comment]
@astjohn : Thanks a lot.:)

**Comment by astjohn** [comment]
No problem!
