### ISSUE TITLE
Strange information from analytics

### ISSUE THREAD

**Issue by pakkux** [Sitata/titanium-google-analytics#26]
Hello,

I started using this module and 2 days later I get really strange readings from analytics. I am still developing it and haven't published this but get reading like people around the world are using my application. The other day got 33 new users. Could this be error in plugin or someone is stealing my source?

**Comment by astjohn** [comment]
Hi @pakkux. Not likely the module. There's nothing strange about it. If you look at the source, it is basically a wrapper around the native SDKs. I have no idea if someone is stealing your source. Hopefully not! Perhaps double check which analytics property tracker ids you are using or make a new one and use the new one to see what happens.
