### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gurmukhp** [Sitata/titanium-google-analytics#28]
Hi there

How do I install this module? I've downloaded the module as a ZIP from github, installed it globally in Titanium but I can't seem to find it when I want to add it to my tiapp.xml.

Am I importing it incorrectly?

**Comment by astjohn** [comment]
You should be able to follow the instructions as per the Appcelerator documentation or this tool:
http://gitt.io/cli

You should also ensure that you have downloaded the module's release zip files and not the entire repositories source code.

**Comment by gurmukhp** [comment]
Thank you for a speedy response!
