### ISSUE TITLE
Android zip

### ISSUE THREAD

**Issue by gurmukhp** [Sitata/titanium-google-analytics#29]
Apologies for opening a new thread, where can I find the android module zip file?

I've found the zip in the ios folder, installed it, but when I go to add it to my app, I'm only shown Google Analytics [ios] and not Android, do I have to install the android one separately?

**Comment by astjohn** [comment]
Yes. I highly encourage your read the Appcelerator documentation and/or the documentation on the site I provided you with. If this is your first attempt at installing a module, the documentation will be extremely useful for you. You need to unzip both an android and an ios module's zip file in the root of your app and then configure your tiapp.xml file separately. Please do read the documentation and try to figure things out before creating an issue. You can always ask people on the Appcelerator community forums as well. This is not a help forum.
