### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by deckameron** [Sitata/titanium-google-analytics#31]
Hi @somi82,

Thank you for this amazing module. 
I have updated it to the newest 3.1.0 version and now my project is show this error:
Could please help me?

[ERROR] :  TiExceptionHandler: (main) [465,34701] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,34701] - In ui/common/DetailWindow.js:1,69
[ERROR] :  TiExceptionHandler: (main) [0,34701] - Message: Uncaught Error: Class 'java.lang.String' does not implement interface 'java.util.Map' in call to 'int java.util.Map.size()' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
[ERROR] :  TiExceptionHandler: (main) [0,34701] - Source: })}))}}),s.addEventListener("focus",function(){Titanium.App.tracker.trackScree
[ERROR] :  V8Exception: Exception occurred at ui/common/DetailWindow.js:1: Uncaught Error: Class 'java.lang.String' does not implement interface 'java.util.Map' in call to 'int java.util.Map.size()' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

**Comment by deckameron** [comment]
Nevermind! I just found the problem.

On the previous version I was using, the TrackScreen method received a String, and now it a {}.
My bad!

**Comment by astjohn** [comment]
No worries. Glad you found the small change. Cheers!
