### ISSUE TITLE
Module not found problem

### ISSUE THREAD

**Issue by jfreak53** [Sitata/titanium-google-analytics#35]
I'm having a problem running an app that my colleagues have running fine on their Macs and Linux machines. Every time I start in the emulator (Android SDK and Genymotion) it tells me that it cannot find the module. But the module is right there.

My colleagues have sent me working zipped versions from their PCs and it still will not compile on mine. Titanium 3.5.1GA is what I am using.

Error:
```
[ERROR] :  TiExceptionHandler: (main) [1722,1722] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [1,1723] - In ti:/module.js:280,9
[ERROR] :  TiExceptionHandler: (main) [1,1724] - Message: Uncaught Error: Requested module not found: analytics.google
[ERROR] :  TiExceptionHandler: (main) [0,1724] - Source:         throw new Error("Requested module not found: " + request);
[ERROR] :  V8Exception: Exception occurred at ti:/module.js:280: Uncaught Error: Requested module not found: analytics.google
```

Versions:
```
$ node -v
v0.12.4
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK Server VM (build 24.79-b02, mixed mode)
$ ti --version
4.0.1

$ ti sdk
Titanium Command-Line Interface, CLI version 4.0.1, Titanium SDK version 3.5.1.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

SDK Install Locations:
   /home/land/.titanium [default]

Installed SDKs:
   3.5.1.GA [selected]  /home/land/.titanium/mobilesdk/linux/3.5.1.GA
```

Here is a full stack page where I am looking for help also showing some SS.
http://stackoverflow.com/questions/30623316/titanium-missing-google-analytics-when-starting-app?noredirect=1#comment49357229_30623316

**Comment by astjohn** [comment]
I can't tell which version of this module you're using, [but this sounds very familiar.](https://github.com/Sitata/titanium-google-analytics/issues/17)

I had hoped the issue was solved by the [latest release](https://github.com/Sitata/titanium-google-analytics/releases/tag/Android-3.1.0-iOS-3.1.0). If that's not the case, please let me know.

**Comment by jfreak53** [comment]
You are my new favorite person on planet earth! :) thank you so much. It's finally working, I've been at it a week and gotten no where haha. Thanks again!

**Comment by astjohn** [comment]
No problem! ...but about the release version...  are you using the new one? It would be helpful to know if the new version solved this issue or not.

**Comment by jfreak53** [comment]
3.0.0: http://cdn.microthosting.com/imgs/Screenshot_at_2015-06-04_16-31-11.png

**Comment by jfreak53** [comment]
Not sure if that is new or old, we inherited the app from another dev. Never used it before :)

**Comment by astjohn** [comment]
No worries. If you have a free moment, try replacing it with the newest version and let me know how it goes. I think we solved that issue, but would love to know for sure.
