### ISSUE TITLE
Google analytics module not working on android, makes the app crash with  ti 3.5.1 sdk

### ISSUE THREAD

**Issue by parween** [Sitata/titanium-google-analytics#36]
[ERROR] : TiApplication: (KrollRuntimeThread) [29,111] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: Couldn't load analytics.google from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.myapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.company.myapp-2, /system/lib]]]: findLibrary returned null; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] : TiApplication: java.lang.UnsatisfiedLinkError: Couldn't load analytics.google from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.myapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.company.myapp-2, /system/lib]]]: findLibrary returned null
[ERROR] : TiApplication: at java.lang.Runtime.loadLibrary(Runtime.java:358)
[ERROR] : TiApplication: at java.lang.System.loadLibrary(System.java:526)
[ERROR] : TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] : TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] : TiApplication: at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] : TiApplication: at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

Also, If you can help us with the libs folder for android module ,as it is not available in this repository.Please help asap.Thanks in advance

**Comment by astjohn** [comment]
Are you sure you're including the module properly. What does your modules folder look like?

I'm also not sure what you mean by the libs folder. Really, all you need to do is unzip the release zip file into the root of your project folder and make an entry in your tiapp.xml file.

**Comment by parween** [comment]
@astjohn : thanks for quick reply.It's working well in iOS. But android version of the app is crashing. I have manually copied the modules folder to application support->titanium->android folder in mac.
