### ISSUE TITLE
Error to connect to Google Play services with sdk Google Analytics 7.5.71

### ISSUE THREAD

**Issue by squirrelsquare** [Sitata/titanium-google-analytics#37]
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

Same error with master build form github.

Full log for 7.5.71
[INFO] :   GAv4: Google Analytics 7.5.71 is starting up. To enable debug logging on a device run:
[INFO] :   GAv4:   adb shell setprop log.tag.GAv4 DEBUG
[INFO] :   GAv4:   adb logcat -s GAv4
[WARN] :   GAv4: AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.g
l/8Rd3yj for instructions.
[INFO] :   I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/14/15, ab0075f, Id3510ff6dc
[WARN] :   GAv4: CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3
yj for instructions.
[INFO] :   OpenGLRenderer: Initialized EGL, version 1.4
[WARN] :   GAv4: AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
[INFO] :   a87c8390300c98f4
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included

And full log for master build
[WARN] :   dalvikvm: VFY: unable to resolve static field 8529 (common_google_play_services_install_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8524 (common_google_play_services_enable_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8543 (common_google_play_services_update_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8521 (common_android_wear_update_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8540 (common_google_play_services_unsupported_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8534 (common_google_play_services_network_error_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8531 (common_google_play_services_invalid_account_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8538 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8528 (common_google_play_services_install_text_tablet) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8527 (common_google_play_services_install_text_phone) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8523 (common_google_play_services_enable_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8542 (common_google_play_services_update_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8520 (common_android_wear_update_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8539 (common_google_play_services_unsupported_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8533 (common_google_play_services_network_error_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8530 (common_google_play_services_invalid_account_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8526 (common_google_play_services_install_button) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8522 (common_google_play_services_enable_button) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8541 (common_google_play_services_update_button) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8538 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8535 (common_google_play_services_notification_needs_installation_title) in Lcom/google/android/gms/R$s
tring;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8536 (common_google_play_services_notification_needs_update_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8519 (common_android_wear_notification_needs_update_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8532 (common_google_play_services_needs_enabling_title) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8539 (common_google_play_services_unsupported_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8533 (common_google_play_services_network_error_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8530 (common_google_play_services_invalid_account_text) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8538 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8525 (common_google_play_services_error_notification_requested_by_msg) in Lcom/google/android/gms/R$str
ing;
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x2141 at 0x35 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x2140 at 0x67 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x2160 at 0x69 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x2159 at 0x87 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included

**Comment by astjohn** [comment]
Are you sure you're using this module? I don't recognize the `GAv4` log messages. In either case, please refer to the [README](https://github.com/Sitata/titanium-google-analytics#google-play-services). One other user had this problem and it was due to the fact that some of the libraries were not installed on his local environment. Also ensure that the phone has Google Play Services, but this is likely not the issue.
