### ISSUE TITLE
Debugging if GA Tracker is Firing

### ISSUE THREAD

**Issue by victsant** [Sitata/titanium-google-analytics#38]
Hi,

Is there a way to check if the trackScreen or trackEvent is firing through the command line instead of looking in Google Anayltics dashboard.

Thanks,
Victor

**Comment by astjohn** [comment]
I don't believe there are any log messages from within the module. However, it is most definitely firing. It can take as long as 48 hours for Google to display the results.

**Comment by victsant** [comment]
Hi,

Ok, thank you.

Thanks,
Victor
