### ISSUE TITLE
Do we need to install Google Configurations?

### ISSUE THREAD

**Issue by gdblack** [Sitata/titanium-google-analytics#47]
Hello,

While following the google-analytics instructions for mobile implementation there is a button to generate and download configs for both android and ios. Do we need those for this module to function as expected? If so, can you provide some direction on where I need to place these files in my Ti project?

Thanks,
Grant

**Comment by astjohn** [comment]
This shouldn't be necessary as the module will the tracker id that you give it through:

```
var tracker = GA.getTracker("UA-1234567-8");
```

Note that [there's currently an issue](https://github.com/Sitata/titanium-google-analytics/issues/48) with new versions of titanium and associated modules that will hopefully be resolved soon.
