### ISSUE TITLE
Tracker.trackScreen issues

### ISSUE THREAD

**Issue by rpavez** [Sitata/titanium-google-analytics#50]
Tracker.trackScreen(params) not working for me, Ti 3.5.1.GA iOS 9. Any idea how to fix it? events are working so its not a problem fetching the tracker or something else.

**Comment by univers3** [comment]
Same here!
@rpavez have you solved this issue?
TrackScreen make crash my app on IOS 9.

**Comment by rpavez** [comment]
Sorry @univers3 I haven't I'm actually thinking on moving on from Titanium..

**Comment by soumyakantikar** [comment]
Is the sample application working for you? Can you please test it and confirm. If not, then we can go back and look into it. Currently, it is working for me on iOS 9, though I have built the application using 3.5.0.GA and planning to move to 5.2.0.GA
