### ISSUE TITLE
AnalyticsGoogleTrackerProxy Invalid type passed to function

### ISSUE THREAD

**Issue by cayaumas1** [Sitata/titanium-google-analytics#52]
Error on build:
Titanium SDK 5.1.2.GA
iOS simulator iPhone 4s and 5, iOS 8.3

Error log:
`ERROR] :  The application has crashed with an uncaught exception 'org.bancosgt.AnalyticsGoogleTrackerProxy'.
[ERROR] :  Reason:
[ERROR] :  Invalid type passed to function
[ERROR] :  Stack trace:
[ERROR] :  
[ERROR] :  0   CoreFoundation                      0x059ad72a __exceptionPreprocess + 154
[ERROR] :  1   libobjc.A.dylib                     0x05580a97 objc_exception_throw + 44
[ERROR] :  2   BancosGT                            0x00116918 TiExceptionThrowWithNameAndReason + 232
[ERROR] :  3   BancosGT                            0x000e2c5f -[TiProxy throwException:subreason:location:] + 143
[ERROR] :  4   BancosGT                            0x006eb926 -[AnalyticsGoogleTrackerProxy trackException:] + 816
[ERROR] :  5   libobjc.A.dylib                     0x05596771 -[NSObject performSelector:withObject:] + 70
[ERROR] :  6   BancosGT                            0x006ebba6 __46-[AnalyticsGoogleTrackerProxy trackException:]_block_invoke + 51
[ERROR] :  7   BancosGT                            0x001176ac __TiThreadPerformOnMainThread_block_invoke + 60
[ERROR] :  8   BancosGT                            0x00117b20 TiThreadProcessPendingMainThreadBlocks + 528
[ERROR] :  9   BancosGT                            0x001178f9 __TiThreadPerformOnMainThread_block_invoke216 + 57
[ERROR] :  10  libdispatch.dylib                   0x088e0d8a _dispatch_call_block_and_release + 15
[ERROR] :  11  libdispatch.dylib                   0x088fdecf _dispatch_client_callout + 14
[ERROR] :  12  libdispatch.dylib                   0x088e6ee3 _dispatch_main_queue_callback_4CF + 677
[ERROR] :  13  CoreFoundation                      0x059068ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
[ERROR] :  14  CoreFoundation                      0x058c45f0 __CFRunLoopRun + 2256
[ERROR] :  15  CoreFoundation                      0x058c3a5b CFRunLoopRunSpecific + 443
[ERROR] :  16  CoreFoundation                      0x058c388b CFRunLoopRunInMode + 123
[ERROR] :  17  GraphicsServices                    0x05dd72c9 GSEventRunModal + 192
[ERROR] :  18  GraphicsServices                    0x05dd7106 GSEventRun + 104
[ERROR] :  19  UIKit                               0x03008106 UIApplicationMain + 1526
[ERROR] :  20  BancosGT                            0x00004988 main + 408
[ERROR] :  21  libdyld.dylib                       0x08923ac9 start + 1
[ERROR] :  
[ERROR] :  2016-02-03 16:08:51.694 BancosGT[51687:3481944] *** Terminating app due to uncaught exception 'org.bancosgt.AnalyticsGoogleTrackerProxy', reason: 'Invalid type passed to function'
[ERROR] :  *** First throw call stack:
[ERROR] :  (
[ERROR] :  	0   CoreFoundation                      0x059ad746 __exceptionPreprocess + 182
[ERROR] :  	1   libobjc.A.dylib                     0x05580a97 objc_exception_throw + 44
[ERROR] :  	2   BancosGT                            0x00116918 TiExceptionThrowWithNameAndReason + 232
[ERROR] :  	3   BancosGT                            0x000e2c5f -[TiProxy throwException:subreason:location:] + 143
[ERROR] :  	4   BancosGT                            0x006eb926 -[AnalyticsGoogleTrackerProxy trackException:] + 816
[ERROR] :  	5   libobjc.A.dylib                     0x05596771 -[NSObject performSelector:withObject:] + 70
[ERROR] :  	6   BancosGT                            0x006ebba6 __46-[AnalyticsGoogleTrackerProxy trackException:]_block_invoke + 51
[ERROR] :  	7   BancosGT                            0x001176ac __TiThreadPerformOnMainThread_block_invoke + 60
[ERROR] :  	8   BancosGT                            0x00117b20 TiThreadProcessPendingMainThreadBlocks + 528
[ERROR] :  	9   BancosGT                            0x001178f9 __TiThreadPerformOnMainThread_block_invoke216 + 57
[ERROR] :  	10  libdispatch.dylib                   0x088e0d8a _dispatch_call_block_and_release + 15
[ERROR] :  	11  libdispatch.dylib                   0x088fdecf _dispatch_client_callout + 14
[ERROR] :  	12  libdispatch.dylib                   0x088e6ee3 _dispatch_main_queue_callback_4CF + 677
[ERROR] :  	13  CoreFoundation                      0x059068ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
[ERROR] :  	14  CoreFoundation                      0x058c45f0 __CFRunLoopRun + 2256
[ERROR] :  	15  CoreFoundation                      0x058c3a5b CFRunLoopRunSpecific + 443
[ERROR] :  	16  CoreFoundation                      0x058c388b CFRunLoopRunInMode + 123
[ERROR] :  	17  GraphicsServices                    0x05dd72c9 GSEventRunModal + 192
[ERROR] :  	18  GraphicsServices                    0x05dd7106 GSEventRun + 104
[ERROR] :  	19  UIKit                               0x03008106 UIApplicationMain + 1526
[ERROR] :  	20  BancosGT                            0x00004988 main + 408
[ERROR] :  	21  libdyld.dylib                       0x08923ac9 start + 1
[ERROR] :  )
[ERROR] :  libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by soumyakantikar** [comment]
Is this happening always / happens for the first call or sporadic? Did you
try it on device?

**Comment by cayaumas1** [comment]
It's happening always on iOS simulator when build for iPhone 4s and 5, but works with iPhone 5s and newer, i haven't test on device jet.

**Comment by cayaumas1** [comment]
This problem was generated by a bat update of XCode.

**Comment by soumyakantikar** [comment]
Great. Thanks for the update. Cheers.

**Comment by soumyakantikar** [comment]
@cayaumas1  Can you close the issue if proper XCode update resolved the issue for you.
